# Generated by Django 5.2.3 on 2025-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'نوشیدنی سرد'), (2, 'نوشیدنی گرم'), (3, 'نوشیدنی دمی'), (4, 'کیک'), (5, 'غذا')], default=None, null=True),
        ),
    ]
